[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "out_functions" # or wherever your built serverless functions are located
